merchants/urls.py
from django.urls import  path, include
from . import views
from rest_framework import routers

app_name = 'merchants'
# router = routers.DefaultRouter()
# router.register('merchants', views.MerchantView)
urlpatterns = [
    # ex: /merchants/
    path('merchants/', views.IndexView.as_view(), name='index'),
    # ex: /merchants/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    # path('', include(router.urls))
]

myfirstdjangoproject/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from merchants import views

urlpatterns = [
    path('', include('merchants.urls')),
    path('admin/', admin.site.urls),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/token', TokenObtainPairView.as_view()),
    # path('api/token/refresh', TokenRefreshView.as_view()),
]

merchants/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from model_utils import Choices

class Merchant(models.Model):
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    email_address = models.EmailField(max_length=254)
    phone_number = PhoneNumberField()
    fax_number = PhoneNumberField(blank=True)
    LOYALTY = Choices((0, 'gold', 'Gold'), (1, 'star', 'Star'), (2, 'platinum', 'Platinum'))
    loyalty = models.IntegerField(choices=LOYALTY, default=LOYALTY.gold)

    def __str__(self):
        return self.name

merchants/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from merchants.models import Merchant

class NewForm(forms.ModelForm):
    name = forms.CharField(max_length=200)
    location = forms.CharField(max_length=200)
    email_address = forms.EmailField(max_length=254)
    phone_number = PhoneNumberField()
    fax_number = PhoneNumberField()

    class Meta:
        model = Merchant
        fields = ('name', 'location', 'email_address', 'phone_number', 'fax_number',)

merchants/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic
from merchants.forms import NewForm
from rest_framework import viewsets
from .serializers import MerchantSerializer
import requests
from bs4 import BeautifulSoup

from .models import Merchant

class IndexView(generic.ListView):
    template_name = 'merchants/index.html'
    context_object_name = 'merchants_list'

    def get_queryset(self):
        return Merchant.objects.order_by('name')

class DetailView(generic.DetailView):
    model = Merchant
    template_name = 'merchants/detail.html'

def new(request):
    form = NewForm()
    return render(request, 'merchants/new.html', { 'form': form } )

def create(request):
    form = NewForm(request.POST)
    try:
        new_merchant = form.save()
    except:
        return render(request, 'merchants/new.html', {
            'from': form, 'error_message': "Something went wrong",
        })
    else:
        return HttpResponseRedirect(reverse('merchants:detail', args=(new_merchant.id)))

class MerchantView(viewsets.ModelViewSet):
    queryset = Merchant.objects.all()
    serializer_class = MerchantSerializer

merchants/templates/merchants/detail.html
<h1>Name: {{ merchant.name }}</h1>
<h1>Location: {{ merchant.location }}</h1>
<h1>Email: {{ merchant.email_address }}</h1>
<h1>Phone: {{ merchant.phone_number }}</h1>
{% if merchant.fax_number %}
  <h1>Fax: {{ merchant.fax_number }}</h1>
{% endif %}
<h1>Loyalty: {{ merchant.loyalty }}</h1>

merchants/templates/merchants/index.html
<h1>Merchants List</h1>
<a href="{% url 'merchants:new' %}">Add new merchant</a>
{% if merchants_list %}
  <table>
    <thead>
      <th>Name</th>
      <th>Location</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Fax</th>
      <th>Action</th>
    </thead>
    <tbody>
      {% for merchant in merchants_list %}
        <tr>
          <td>{{ merchant.name }}</td>
          <td>{{ merchant.location }}</td>
          <td>{{ merchant.email_address }}</td>
          <td>{{ merchant.phone_number }}</td>
          <td>{{ merchant.fax_number }}</td>
          <td><a href="{% url 'merchants:detail' merchant.id %}">Show</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>No merchants available</p>
{% endif %}

merchants/templates/merchants/new.html
<h1>New Merchant</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form class="new-merchant" action="{% url 'merchants:create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create">
</form>